name: Publish Binary to S3
on:
  push:
    branches:
      - "port/macos-arm64"
      - "master"
  release:
    types: [created]

jobs:
  publish:
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: 'google-github-actions/setup-gcloud@v0'
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: yarn install
      - run: yarn node-pre-gyp unpublish
      - run: yarn publish-binary
